import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";


const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Elearning App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <h1 className="p-8 text-4xl text-red-900 font-bold ">
        E-learning project
      </h1>
      {/* <h2 className="p-8 text-xl font-semibold text-black-700">
        Click the below button
      </h2> */}
      <button className="text-white m-8 bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-2xl text-md px-8 py-4 text-center mr-2 mb-2">
       <Link href="/login">Login</Link>
      </button>
      <button className="text-white m-8 bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-2xl text-md px-8 py-4 text-center mr-2 mb-2">
       <Link href="/otp"> OTP </Link>
      </button>
      <button className="text-white m-8 bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-2xl text-md px-8 py-4 text-center mr-2 mb-2">
       <Link href="/signup"> Sign Up</Link>
      </button>
      <button className="text-white m-8 bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-2xl text-md px-8 py-4 text-center mr-2 mb-2">
       <Link href="/elearninghome"> E-learning Homepage</Link>
      </button>
      <button className="text-white m-8 bg-gradient-to-r from-red-400 via-red-500 to-red-600 hover:bg-gradient-to-br focus:ring-4 focus:outline-none focus:ring-red-300 dark:focus:ring-red-800 font-medium rounded-2xl text-md px-8 py-4 text-center mr-2 mb-2">
       <Link href="/Form"> Form</Link>
      </button>
    </div>
  );
};

export default Home;
